spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.0.0.94/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  freemarker:
    suffix: .ftl
  redis:
    host: 10.0.0.94
    port: 6379
server:
  servlet:
    context-path: /sell
wechat:
  # My test account
  mpAppId: wx6d955bab5296e262
  mpAppSecret: 8cb81dd792feb2a8f07436c81599b5da
  templateId:
    orderStat: lBRqResUbSkE6ZB29LrYJk842m2Cv55yfU2pM0QqG6I
  # Borrowed account
#  mpAppId: wxd898fcb01713c658
#  mpAppSecret:
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 7mdApPMfXddfWWbbP4DUaVYm2wjyh3v3
  keyPath: /Users/fanzhibo/Desktop/learning/project/spring_order/src/main/resources/h5.p12
  notifyUrl: http://zbfan.natapp1.cc/sell/pay/notify
project-url:
  wechatMpAuthorize: http://zbfan.natapp1.cc/
  wechatOpenAuthorize: http://sell.springboot.cn/
  sell: http://zbfan.natapp1.cc/
logging:
  level:
    com.zbfan.spring_order.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml

